### ISSUE TITLE
Artifacts at x16 upscale

### ISSUE THREAD

**Issue by UnblessedSouls** [Sebanisu/Field-Map-Editor#105]
I dont think these black lines were present at x4 upscale but at x16 they are present at first I thought it was because some pixels were transparent at the mask layer but even with changing to solid black it persists. 
![Screenshot 2024-12-20 163901](https://github.com/user-attachments/assets/3d929b6a-48d1-4b0d-94dd-c9f8b761a1cc)

**Comment by Sebanisu** [comment]
Those lines might be from some sort of math error. What field is this from. Could you list a few steps to help reproduce the problem? I haven't looked at this on a bit so might be hard for me to figure it out right away

**Comment by UnblessedSouls** [comment]
I tried x16 upscale on a different field with animations and there was no black lines, its elview2 heres the link to the files
https://www.dropbox.com/scl/fo/no84fb6lk3j2us9nta2do/APLOuZbXX8pMnsY2-cKO8EA?rlkey=wfocy7z3gt2tqmdxir01gxhh9&st=zh9nlmtx&dl=0

**Comment by Sebanisu** [comment]
I just spent 2 days getting things to compile again. lol. now is Christmas. There were some new bugs surfaced. I'm gonna try to knock out the bugs and hopefully get to this before the end of my Christmas break.

**Comment by Sebanisu** [comment]
I do wonder how you generated these. I'm gonna try to output some my self and upscale them, and compare.

**Comment by Sebanisu** [comment]
> I dont think these black lines were present at x4 upscale but at x16 they are present at first I thought it was because some pixels were transparent at the mask layer but even with changing to solid black it persists. ![Screenshot 2024-12-20 163901](https://private-user-images.githubusercontent.com/119603782/397944591-3d929b6a-48d1-4b0d-94dd-c9f8b761a1cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU1Mjk5NzUsIm5iZiI6MTczNTUyOTY3NSwicGF0aCI6Ii8xMTk2MDM3ODIvMzk3OTQ0NTkxLTNkOTI5YjZhLTQ4ZDEtNGIwZC05NGRkLWM5ZjhiNzYxYTFjYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIzMFQwMzM0MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZDI2NDhhMDc4YjYzMTlhOWE4MDY3OWFjMDQ2Y2ZiYTlmMTlmYzJjOTA5MTk5YzI0ODFhNjM3NjAwYzg5YzE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.VWoISdEgsj43cidsQPczWUpiOrSBD7idAO9EZz8glJk)

This screen shot from in game?

**Comment by Sebanisu** [comment]
I did notice your pack is missing these elview2_0_1, elview2_0_6, elview2_0_7
those extra images are generated when some tiles are overlapping. Though I dunno if the game can read them yet.
![elview2_0_1](https://github.com/user-attachments/assets/f33ccc4c-3d02-4d4d-8372-a48b9abf827a)
![elview2_0_6](https://github.com/user-attachments/assets/db3023f8-afb4-4453-8ca8-09706ddbafce)
![elview2_0_7](https://github.com/user-attachments/assets/c398dfd9-de53-44c0-97d9-8eecb9fa3ed1)

might not be causing your issue though

**Comment by Sebanisu** [comment]
![image](https://github.com/user-attachments/assets/d72151b0-68a9-4931-987f-63c1bbd421f9)
![image](https://github.com/user-attachments/assets/a5d52024-be2c-4222-894a-1bc04b8d236e)
![elview2_0_with_red_highlights](https://github.com/user-attachments/assets/7e94c9a7-a855-454d-88af-522d1a2a0401)
so I upscaled that one image 16X and made all the non transparent pixels red. and overlaid your image and you can see the red showing through. I think this means that your missing some data in those pixels.

**Comment by UnblessedSouls** [comment]
I always deleted those extra layers because I thought they caused issues with animations? Maybe not? So I redid the layers again with original upscaled and it seems fixed now.

![Screenshot 2024-12-30 110603](https://github.com/user-attachments/assets/ab398e0f-9836-45f5-9252-b6f3bf4a9e45)

But sometimes the blocky layers can cause problems such as this one if I try editing the texture in its swizzled state it becomes black, whats the best way to smooth the edges out?
![Screenshot 2024-12-30 111206](https://github.com/user-attachments/assets/cf7c314e-3ac5-4255-a8d4-fbd6930f588a)

**Comment by UnblessedSouls** [comment]
I managed to fix it by editing the layers before swizzling, then I had to add on areas that was cut off by the swizzle process thanks its all fixed now 
![Screenshot 2024-12-30 125132](https://github.com/user-attachments/assets/b2bf25d3-8b36-45cb-922d-d1c536b0eb5f)

**Comment by Sebanisu** [comment]
i see ya figured that out.

> I managed to fix it by editing the layers before swizzling, then I had to add on areas that was cut off by the swizzle process thanks its all fixed now ![Screenshot 2024-12-30 125132](https://private-user-images.githubusercontent.com/119603782/399294834-b2bf25d3-8b36-45cb-922d-d1c536b0eb5f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU1NjU2MjUsIm5iZiI6MTczNTU2NTMyNSwicGF0aCI6Ii8xMTk2MDM3ODIvMzk5Mjk0ODM0LWIyYmYyNWQzLThiMzYtNDVjYi05MjJkLWQxYzUzNmIwZWI1Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIzMFQxMzI4NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YWQzYjQ0YjM0ZGM3NDRmMGE5OWY1OTE3NmY5ZTI0NzkzNzFmM2I2Yjg3ZDQ3ZTY3MWMyMzlkNDg1ZGI0M2M2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.INNXM947I0PIgNeVbyblDACO05dXRvw0vkAzEV2KAcc)

![image](https://github.com/user-attachments/assets/b320eb14-67ff-4af5-8ef7-641e7ab8fd82)
Blockiness is caused by the 16x16 tiles being blown up. it's less of an issue where the overlapping pixels don't have characters walking behind them. Just gotta make sure the two tiles the game sees still touch in the end. :)
