### ISSUE TITLE
Issues with the Program

### ISSUE THREAD

**Issue by UnblessedSouls** [Sebanisu/Field-Map-Editor#88]
The program sometimes produces additional layers in the swizzle process and will need to be deleted to stop glitches such as the clown in galbadia randomly disappearing.

When you mass export the fields, some layers will have random missing black pixels, this creates issues when you ai upscale, I have to manually edit them to fill the black pixels in which takes a long time. Is there a way to keep those black pixels in when you export?

bgmd2_6 - this field only allows one layer to upscale

glclub1 - the close up seated field doesn't show and cant be upscaled, in game both fields are not working.

bvtr_1 and bvtr_4 - these fields glitch in game, the train background outside glitches, attempting to fix this create issues with the door.

cdfield7 - The exported lighting layers are named incorrectly, changing the first number to 8 fixes them not appearing in the upscale.
              cdfield7_**0**0100000
              cdfield7_**0**0101000
              cdfield7_**0**0102000

crtower3 - top part of torch pilar is glitched, showing yellow flame instead of black stone

Will update if I find more issues

**Comment by Sebanisu** [comment]
Thanks for report. I will try to look at it asap. I work weekends. I'll let ya know.

**Comment by Sebanisu** [comment]
https://github.com/Sebanisu/Field-Map-Editor/issues/89 for bvtr_1 and bvtr_4

**Comment by Sebanisu** [comment]
bgmd2_6 maybe check your file names? everything seems file to me.
![image](https://user-images.githubusercontent.com/1035905/206238386-498a3073-182d-40bd-ab49-06d8221d5b09.png)

**Comment by Sebanisu** [comment]
glclub1 looks right but when swizzling there is a possible palette conflict. see #89.
![image](https://user-images.githubusercontent.com/1035905/206239302-986ffc95-5952-4711-acf0-fbd511cbe893.png)
check your file names and check to see if your using the most up to date canary build.

**Comment by UnblessedSouls** [comment]
Hmm well when I did extract the field files it was from a build in late June, seems the names are different. 
I will re extract and see if it fixes them.

https://imgur.com/a/zWeWyXW

**Comment by Sebanisu** [comment]
You don't need to use imgur.com github should let you paste images into the message.

I think I made that change in like august or september, also fixed a few other bugs since then.
